# Generated by Django 4.2.8 on 2024-01-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_bot_lead_leadbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='bot',
        ),
    ]
