# Generated by Django 4.2.8 on 2024-01-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_lead_bot_token_lead_grupo_delete_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='grupo',
            new_name='chat',
        ),
    ]
